### ISSUE TITLE
raw bam or realigned bam

### ISSUE THREAD

**Issue by wangjiawen2013** [varlociraptor/varlociraptor#140]
Hi,
When I use varlociraptor preprocess variants, I'm not sure about the bam. Does varlociraptor require raw bam or realigned bam file (such as realigned by GATK IndelRealigner to improve alignments around indels)?

**Comment by dlaehnemann** [comment]
Hi @wangjiawen2013 ,
indel realignment should not be necessary, because varlociraptor will effectively realign internally (via a pairHMM) whenever necessary. One thing that you could do in preprocessing, and of which we have seen effects in the output, is to recalibrate the base qualities, i.e. GATK `BaseRecalibrator`. For a way to do easily do this in a snakemake pipeline, check out the snakemake wrapper:
https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/gatk/baserecalibrator.html

**Comment by dlaehnemann** [comment]
Also, for best practices on using varlociraptor, you could have a look at the respective snakemake workflow:
https://github.com/snakemake-workflows/dna-seq-varlociraptor

I'll close this issue for now, but feel free to reopen it, if these points don't sufficiently answer your question.
