### ISSUE TITLE
RNA Editing scenario

### ISSUE THREAD

**Issue by kokyriakidis** [varlociraptor/varlociraptor#195]
Hi,

Can you propose a scenario for the detection of RNA-Editing Events? Is it possible?

**Comment by johanneskoester** [comment]
Good question. I would think that one could detect this easily when having a scenario with both a dna and an rna sample, right? In that case, all variants that are exclusive to the RNA sample should be editing events. Does that make sense for you? If you, I'll be happy to provide a scenario in the scenario catalog, just let me know.

**Comment by kokyriakidis** [comment]
@johanneskoester 

I have **only** RNASeq data. Let's say I use GATK to call variants in these RNASeq data. I don't trust the hard filters they use for RNASeq data because they may treat potential RNAEditing events as FPs. How possible it is that Varcoliraptor will treat such events (A-to-I or C-to-U sites) as FPs and label them as ARTIFACTS?

**Comment by kokyriakidis** [comment]
I just want all heterozygous sites AND all RNA editing events in one big bucket, without the latter filtered out as artifacts.

**Comment by dlaehnemann** [comment]
Then, simply defining a scenario that looks for non-zero alternative allele frequencies in you sample should do the trick. Basically, this scenario:
https://varlociraptor.github.io/varlociraptor-scenarios/scenarios/rna-seq-variant-calling/

And then check whether you expect any of the biases mentioned above to be present in your data due to the RNA -> DNA -> sequencing library protocol and turn them off while calling.
